### ISSUE TITLE
Indented codeblocks throw off all future codeblocks

### ISSUE THREAD

**Issue by Earlopain** [rubocop/rubocop-md#28]
rubocop.yml
```yml
require:
  - rubocop-md

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
```
![grafik](https://github.com/rubocop/rubocop-md/assets/14981592/fe0e297d-9ae7-4e99-b326-3c1586bd2509)
![grafik](https://github.com/rubocop/rubocop-md/assets/14981592/09a6ee75-604b-4026-8a1b-e67c4285037f)

[test.md](https://github.com/rubocop/rubocop-md/files/13646253/test.md) since I still don't know how to properly escape markdown here.

I'll try to check this out myself if that's fine with you @palkan, but in case I don't manage like last time I'll let you know. That good?
